<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'RimAI.Communication.Voices'">
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Voices\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Voices\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'RimAI.Communication.Voices.Tests'">
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Voices.Tests\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Voices.Tests\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
